# Site settings
title: gren
description: > # Node module to publish release notes based on commits between the last two tags.
baseurl: "/github-release-notes"
docsurl: "github-release-notes/"
url: "http://github-tools.github.io/github-release-notes" # the base hostname & protocol for your site
twitter_username: alexcanessa
github_username: alexcanessa

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

redcarpet:
    extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
